sudo: false
dist: trusty
language: node_js
node_js:
- '6'
- '7'
- '8'

cache:
  yarn: true
  directories:
     - ./node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn run test-ci
